{
    "neow_bonuses_skipped_log": [
        "UPGRADE_CARD",
        "TEN_PERCENT_HP_BONUS",
        "BOSS_RELIC"
    ],
    "neow_costs_skipped_log": [
        "NONE",
        "NONE",
        "NONE"
    ],
    "potions_obtained_entropic_brew": [
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        []
    ],
    "gold_per_floor": [
        138,
        21,
        21,
        57,
        88,
        88,
        191,
        191,
        272,
        313,
        313,
        367,
        367,
        455,
        455,
        553,
        553,
        620,
        670,
        707,
        145,
        214,
        273,
        355,
        355,
        405,
        417,
        34,
        71,
        126,
        231,
        231,
        310,
        310,
        352,
        445,
        463,
        174,
        174,
        509,
        509,
        509,
        535,
        592,
        592,
        644,
        644,
        697,
        697,
        767,
        792,
        792,
        792,
        134,
        192,
        192
    ],
    "floor_reached": 57,
    "playtime": 3690,
    "items_purged": [
        "Shame",
        "Strike_R",
        "Strike_R",
        "Strike_R"
    ],
    "score": 3383,
    "play_id": "904fa3d2-b59f-4110-8a11-4e870eb2e0ae",
    "local_time": "20220930133052",
    "score_breakdown": [
        "Floors Climbed (57): 285",
        "Enemies Slain (12): 24",
        "Exordium Elites Killed (2): 20",
        "City Elites Killed (4): 80",
        "Beyond Elites Killed (4): 120",
        "Bosses Slain (5): 750",
        "I Like Shiny: 50",
        "Raining Money (2134): 50",
        "Librarian: 25",
        "Champion (3): 75",
        "Perfect (2): 100",
        "Overkill: 25",
        "C-c-c-combo: 25",
        "Ascension (20): 1504",
        "Heartbreaker: 250"
    ],
    "is_ascension_mode": true,
    "potions_obtained_alchemize": [
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        []
    ],
    "campfire_choices": [
        {
            "data": "HandOfGreed",
            "floor": 6,
            "key": "SMITH"
        },
        {
            "data": "Battle Trance",
            "floor": 8,
            "key": "SMITH"
        },
        {
            "data": "Berserk",
            "floor": 13,
            "key": "SMITH"
        },
        {
            "data": "Dark Embrace",
            "floor": 15,
            "key": "SMITH"
        },
        {
            "floor": 25,
            "key": "REST"
        },
        {
            "data": "Bloodletting",
            "floor": 32,
            "key": "SMITH"
        },
        {
            "data": "Juggernaut",
            "floor": 42,
            "key": "SMITH"
        },
        {
            "floor": 45,
            "key": "RECALL"
        },
        {
            "data": "Feel No Pain",
            "floor": 47,
            "key": "SMITH"
        },
        {
            "data": "Feel No Pain",
            "floor": 49,
            "key": "SMITH"
        },
        {
            "data": "Study",
            "floor": 53,
            "key": "SMITH"
        }
    ],
    "lesson_learned_per_floor": [
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        []
    ],
    "neow_cost": "CURSE",
    "seed_source_timestamp": 626394786700,
    "shop_contents": [
        {
            "floor": 2,
            "relics": [
                "Unceasing Top",
                "Bottled Flame",
                "Medical Kit"
            ],
            "cards": [
                "Headbutt",
                "Sword Boomerang",
                "True Grit",
                "Shrug It Off",
                "Panacea",
                "HandOfGreed"
            ],
            "potions": [
                "SneckoOil",
                "CultistPotion",
                "Strength Potion"
            ]
        },
        {
            "floor": 21,
            "relics": [
                "Torii"
            ],
            "cards": [
                "Hemokinesis",
                "Iron Wave",
                "Warcry",
                "Ghostly Armor",
                "Metallicize",
                "Swift Strike",
                "Thinking Ahead"
            ],
            "potions": [
                "SneckoOil"
            ]
        },
        {
            "floor": 28,
            "relics": [
                "Nunchaku",
                "White Beast Statue"
            ],
            "cards": [
                "Perfected Strike",
                "Feed",
                "Bloodletting",
                "Exhume",
                "Panacea",
                "HandOfGreed"
            ],
            "potions": [
                "LiquidMemories"
            ]
        },
        {
            "floor": 38,
            "relics": [
                "Sundial",
                "Gremlin Horn"
            ],
            "cards": [
                "Reckless Charge",
                "Perfected Strike",
                "Power Through",
                "Burning Pact",
                "Evolve",
                "Jack Of All Trades",
                "Transmutation"
            ],
            "potions": [
                "FearPotion",
                "EntropicBrew",
                "EntropicBrew"
            ]
        },
        {
            "floor": 54,
            "relics": [],
            "cards": [
                "Pummel",
                "Clothesline",
                "Shrug It Off",
                "Havoc",
                "Flash of Steel"
            ],
            "potions": [
                "Weak Potion",
                "Fire Potion"
            ]
        }
    ],
    "circlet_count": 0,
    "master_deck": [
        "AscendersBane",
        "Strike_R",
        "Defend_R",
        "Defend_R",
        "Defend_R",
        "Defend_R",
        "Bash",
        "HandOfGreed+1",
        "Seeing Red",
        "Feel No Pain+1",
        "Dark Embrace+1",
        "Infernal Blade",
        "Battle Trance+1",
        "Headbutt",
        "Berserk+1",
        "Bloodletting+1",
        "Shrug It Off",
        "Juggernaut+1",
        "Carnage",
        "Sever Soul",
        "Endless Agony",
        "Burning Pact",
        "Feel No Pain+1",
        "Storm of Steel",
        "Blade Dance",
        "Core Surge",
        "PiercingWail+1",
        "Tantrum+1",
        "Master of Strategy",
        "FearNoEvil",
        "Study+1",
        "HandOfGreed",
        "Feel No Pain",
        "Apotheosis",
        "Seeing Red+1"
    ],
    "potion_use_per_floor": [
        [],
        [],
        [],
        [],
        [],
        [],
        [
            "Block Potion"
        ],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [
            "FearPotion"
        ],
        [],
        [],
        [],
        [
            "Regen Potion",
            "Regen Potion"
        ],
        [],
        [],
        [
            "ElixirPotion"
        ],
        [
            "Explosive Potion"
        ],
        [],
        [],
        [],
        [],
        [
            "Block Potion"
        ],
        [
            "Explosive Potion"
        ],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [
            "Strength Potion"
        ],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [
            "HeartOfIron",
            "DuplicationPotion",
            "ElixirPotion"
        ],
        []
    ],
    "relics": [
        "Burning Blood",
        "Centennial Puzzle",
        "Red Skull",
        "Letter Opener",
        "WingedGreaves",
        "Black Star",
        "PreservedInsect",
        "PrismaticShard",
        "InkBottle",
        "Matryoshka",
        "Blue Candle",
        "Potion Belt",
        "MawBank",
        "Sling",
        "Thread and Needle",
        "Dead Branch",
        "Pear",
        "Blood Vial",
        "SlaversCollar",
        "ClockworkSouvenir",
        "CaptainsWheel",
        "Old Coin",
        "Pen Nib",
        "Ancient Tea Set",
        "Orichalcum",
        "Bronze Scales",
        "Mummified Hand",
        "Strawberry",
        "StoneCalendar",
        "Omamori",
        "Membership Card",
        "HornCleat",
        "Bag of Preparation",
        "Happy Flower",
        "Oddly Smooth Stone"
    ],
    "potions_floor_usage": [
        7,
        16,
        20,
        20,
        23,
        24,
        29,
        30,
        44,
        56,
        56,
        56
    ],
    "damage_taken": [
        {
            "damage": 5,
            "enemies": "Cultist",
            "floor": 1,
            "turns": 4
        },
        {
            "damage": 1,
            "enemies": "2 Louse",
            "floor": 4,
            "turns": 3
        },
        {
            "damage": 2,
            "enemies": "Jaw Worm",
            "floor": 5,
            "turns": 3
        },
        {
            "damage": 8,
            "enemies": "3 Sentries",
            "floor": 7,
            "turns": 9
        },
        {
            "damage": 6,
            "enemies": "Looter",
            "floor": 10,
            "turns": 2
        },
        {
            "damage": 22,
            "enemies": "Lagavulin",
            "floor": 12,
            "turns": 5
        },
        {
            "damage": 14,
            "enemies": "Gremlin Gang",
            "floor": 14,
            "turns": 5
        },
        {
            "damage": 27,
            "enemies": "The Guardian",
            "floor": 16,
            "turns": 11
        },
        {
            "damage": 26,
            "enemies": "3 Byrds",
            "floor": 18,
            "turns": 5
        },
        {
            "damage": 22,
            "enemies": "Shell Parasite",
            "floor": 20,
            "turns": 8
        },
        {
            "damage": 4,
            "enemies": "Centurion and Healer",
            "floor": 22,
            "turns": 5
        },
        {
            "damage": 27,
            "enemies": "Book of Stabbing",
            "floor": 23,
            "turns": 3
        },
        {
            "damage": 37,
            "enemies": "Slavers",
            "floor": 24,
            "turns": 4
        },
        {
            "damage": 19,
            "enemies": "Snake Plant",
            "floor": 29,
            "turns": 4
        },
        {
            "damage": 6,
            "enemies": "Gremlin Leader",
            "floor": 30,
            "turns": 3
        },
        {
            "damage": 7,
            "enemies": "Slavers",
            "floor": 31,
            "turns": 6
        },
        {
            "damage": 9,
            "enemies": "Automaton",
            "floor": 33,
            "turns": 5
        },
        {
            "damage": 2,
            "enemies": "Orb Walker",
            "floor": 35,
            "turns": 3
        },
        {
            "damage": 7,
            "enemies": "3 Shapes",
            "floor": 36,
            "turns": 10
        },
        {
            "damage": 6,
            "enemies": "Jaw Worm Horde",
            "floor": 37,
            "turns": 2
        },
        {
            "damage": 3,
            "enemies": "Nemesis",
            "floor": 40,
            "turns": 3
        },
        {
            "damage": 8,
            "enemies": "Reptomancer",
            "floor": 44,
            "turns": 2
        },
        {
            "damage": 3,
            "enemies": "Giant Head",
            "floor": 46,
            "turns": 3
        },
        {
            "damage": 0,
            "enemies": "Nemesis",
            "floor": 48,
            "turns": 3
        },
        {
            "damage": 24,
            "enemies": "Awakened One",
            "floor": 50,
            "turns": 4
        },
        {
            "damage": 19,
            "enemies": "Time Eater",
            "floor": 51,
            "turns": 6
        },
        {
            "damage": 8,
            "enemies": "Shield and Spear",
            "floor": 55,
            "turns": 3
        },
        {
            "damage": 16,
            "enemies": "The Heart",
            "floor": 56,
            "turns": 4
        }
    ],
    "green_key_taken_log": 40,
    "seed_played": "-2467744728686448798",
    "neow_bonus_log": {
        "cardsObtained": [
            "Shame"
        ],
        "cardsUpgraded": [],
        "cardsRemoved": [],
        "cardsTransformed": [],
        "relicsObtained": [],
        "maxHpGained": 0,
        "goldGained": 0,
        "damageTaken": 0,
        "goldLost": 0,
        "maxHpLost": 0
    },
    "potions_obtained": [
        {
            "floor": 4,
            "key": "Regen Potion"
        },
        {
            "floor": 5,
            "key": "Block Potion"
        },
        {
            "floor": 7,
            "key": "FearPotion"
        },
        {
            "floor": 16,
            "key": "Regen Potion"
        },
        {
            "floor": 23,
            "key": "ElixirPotion"
        },
        {
            "floor": 29,
            "key": "Explosive Potion"
        },
        {
            "floor": 30,
            "key": "AttackPotion"
        },
        {
            "floor": 31,
            "key": "HeartOfIron"
        },
        {
            "floor": 35,
            "key": "Strength Potion"
        },
        {
            "floor": 46,
            "key": "BlessingOfTheForge"
        }
    ],
    "is_trial": false,
    "path_per_floor": [
        "M",
        "$",
        "?",
        "M",
        "M",
        "R",
        "E",
        "R",
        "T",
        "M",
        "?",
        "E",
        "R",
        "M",
        "R",
        "B",
        null,
        "M",
        "?",
        "M",
        "$",
        "M",
        "E",
        "E",
        "R",
        "T",
        "?",
        "$",
        "M",
        "E",
        "E",
        "R",
        "B",
        null,
        "M",
        "M",
        "M",
        "$",
        "?",
        "E",
        "?",
        "R",
        "T",
        "E",
        "R",
        "E",
        "R",
        "E",
        "R",
        "B",
        "B",
        null,
        "R",
        "$",
        "E",
        "B",
        null
    ],
    "character_chosen": "IRONCLAD",
    "items_purchased": [
        "Feel No Pain",
        "PreservedInsect",
        "PrismaticShard",
        "Explosive Potion",
        "ElixirPotion",
        "Feel No Pain",
        "Sling",
        "Block Potion",
        "LiquidMemories",
        "ClockworkSouvenir",
        "Membership Card",
        "HornCleat",
        "Bag of Preparation",
        "Feel No Pain",
        "Apotheosis",
        "DuplicationPotion"
    ],
    "campfire_rested": 1,
    "item_purchase_floors": [
        2,
        21,
        21,
        21,
        21,
        28,
        28,
        28,
        28,
        38,
        54,
        54,
        54,
        54,
        54,
        54
    ],
    "current_hp_per_floor": [
        69,
        69,
        64,
        69,
        73,
        73,
        71,
        71,
        71,
        71,
        71,
        55,
        55,
        47,
        47,
        26,
        63,
        43,
        43,
        75,
        75,
        75,
        54,
        23,
        45,
        45,
        45,
        45,
        32,
        32,
        41,
        41,
        40,
        74,
        80,
        81,
        83,
        83,
        83,
        85,
        81,
        81,
        81,
        79,
        79,
        88,
        88,
        88,
        88,
        70,
        59,
        81,
        81,
        81,
        81,
        73
    ],
    "gold": 192,
    "neow_bonus": "RANDOM_COLORLESS_2",
    "is_prod": false,
    "is_daily": false,
    "rewards_skipped": [
        {
            "floor": 18,
            "relics": [],
            "potions": [
                "CultistPotion"
            ]
        },
        {
            "floor": 48,
            "relics": [],
            "potions": [
                "FearPotion"
            ]
        },
        {
            "floor": 55,
            "relics": [],
            "potions": [
                "Dexterity Potion"
            ]
        }
    ],
    "chose_seed": false,
    "campfire_upgraded": 9,
    "win_rate": 0,
    "floor_exit_playtime": [
        55,
        63,
        66,
        96,
        134,
        142,
        231,
        246,
        249,
        272,
        296,
        378,
        388,
        483,
        498,
        621,
        672,
        777,
        789,
        926,
        989,
        1066,
        1180,
        1294,
        1298,
        1312,
        1344,
        1404,
        1525,
        1612,
        1737,
        1756,
        1939,
        1985,
        2043,
        2194,
        2275,
        2323,
        2326,
        2457,
        2472,
        2485,
        2492,
        2590,
        2595,
        2693,
        2704,
        2787,
        2795,
        3071,
        3221,
        3272,
        3307,
        3326,
        3455,
        3690
    ],
    "timestamp": 1664559052,
    "blue_key_relic_skipped_log": {
        "floor": 26,
        "relicID": "Akabeko"
    },
    "path_taken": [
        "M",
        "$",
        "?",
        "M",
        "M",
        "R",
        "E",
        "R",
        "T",
        "M",
        "?",
        "E",
        "R",
        "?",
        "R",
        "BOSS",
        "M",
        "?",
        "M",
        "$",
        "M",
        "E",
        "E",
        "R",
        "T",
        "?",
        "$",
        "M",
        "E",
        "E",
        "R",
        "BOSS",
        "M",
        "?",
        "M",
        "$",
        "?",
        "E",
        "?",
        "R",
        "T",
        "E",
        "R",
        "E",
        "R",
        "E",
        "R",
        "BOSS",
        "BOSS",
        "R",
        "$",
        "E",
        "BOSS"
    ],
    "build_version": "2022-03-07",
    "purchased_purges": 4,
    "victory": true,
    "max_hp_per_floor": [
        75,
        75,
        75,
        75,
        75,
        75,
        75,
        75,
        75,
        75,
        75,
        75,
        75,
        75,
        75,
        75,
        75,
        75,
        75,
        75,
        75,
        75,
        75,
        75,
        75,
        75,
        75,
        75,
        75,
        75,
        85,
        85,
        85,
        85,
        85,
        85,
        85,
        85,
        85,
        85,
        81,
        81,
        81,
        81,
        81,
        88,
        88,
        88,
        88,
        88,
        88,
        88,
        88,
        88,
        88,
        88
    ],
    "relic_stats": {
        "Happy Flower": [
            1
        ],
        "counters": [
            28,
            128
        ],
        "Blue Candle": [
            1
        ],
        "Dead Branch": [
            294
        ],
        "StoneCalendar": [
            0
        ],
        "PreservedInsect": 558,
        "Pen Nib": [
            13
        ],
        "Omamori": 0,
        "Bag of Preparation": [
            4
        ],
        "Letter Opener": [
            260
        ],
        "Orichalcum": [
            0
        ],
        "MawBank": 24,
        "Ancient Tea Set": [
            8
        ],
        "Burning Blood": 153,
        "Blood Vial": 18,
        "Centennial Puzzle": [
            77
        ],
        "Matryoshka": 2,
        "Mummified Hand": [
            57
        ],
        "Bronze Scales": [
            103
        ],
        "WingedGreaves": 3,
        "Black Star": 9,
        "Membership Card": 493,
        "obtain_stats": [
            {
                "StoneCalendar": 48,
                "Bag of Preparation": 54,
                "PrismaticShard": 21,
                "Sling": 28,
                "Ancient Tea Set": 43,
                "Burning Blood": 0,
                "ClockworkSouvenir": 38,
                "Old Coin": 40,
                "Blood Vial": 31,
                "Centennial Puzzle": 3,
                "Matryoshka": 23,
                "HornCleat": 54,
                "Mummified Hand": 46,
                "Strawberry": 46,
                "WingedGreaves": 12,
                "Red Skull": 7,
                "InkBottle": 23,
                "Potion Belt": 24,
                "Pear": 31,
                "Happy Flower": 55,
                "Blue Candle": 24,
                "Dead Branch": 30,
                "Oddly Smooth Stone": 55,
                "Thread and Needle": 30,
                "PreservedInsect": 21,
                "Pen Nib": 43,
                "Omamori": 48,
                "Letter Opener": 9,
                "Orichalcum": 44,
                "MawBank": 26,
                "SlaversCollar": 34,
                "CaptainsWheel": 40,
                "Bronze Scales": 44,
                "Black Star": 17,
                "Membership Card": 54
            },
            {
                "StoneCalendar": 24,
                "Bag of Preparation": 26,
                "PrismaticShard": 10,
                "Sling": 13,
                "Ancient Tea Set": 21,
                "Burning Blood": 0,
                "ClockworkSouvenir": 20,
                "Old Coin": 21,
                "Blood Vial": 16,
                "Centennial Puzzle": 1,
                "Matryoshka": 12,
                "HornCleat": 26,
                "Mummified Hand": 23,
                "Strawberry": 23,
                "WingedGreaves": 6,
                "Red Skull": 4,
                "InkBottle": 12,
                "Potion Belt": 13,
                "Pear": 16,
                "Happy Flower": 27,
                "Blue Candle": 13,
                "Dead Branch": 15,
                "Oddly Smooth Stone": 27,
                "Thread and Needle": 15,
                "PreservedInsect": 10,
                "Pen Nib": 21,
                "Omamori": 24,
                "Letter Opener": 4,
                "Orichalcum": 22,
                "MawBank": 13,
                "SlaversCollar": 17,
                "CaptainsWheel": 21,
                "Bronze Scales": 22,
                "Black Star": 8,
                "Membership Card": 26
            },
            {
                "StoneCalendar": 111,
                "Bag of Preparation": 121,
                "PrismaticShard": 55,
                "Sling": 67,
                "Ancient Tea Set": 103,
                "Burning Blood": 0,
                "ClockworkSouvenir": 100,
                "Old Coin": 103,
                "Blood Vial": 80,
                "Centennial Puzzle": 4,
                "Matryoshka": 63,
                "HornCleat": 121,
                "Mummified Hand": 108,
                "Strawberry": 108,
                "WingedGreaves": 26,
                "Red Skull": 19,
                "InkBottle": 63,
                "Potion Belt": 67,
                "Pear": 80,
                "Happy Flower": 124,
                "Blue Candle": 67,
                "Dead Branch": 74,
                "Oddly Smooth Stone": 124,
                "Thread and Needle": 74,
                "PreservedInsect": 55,
                "Pen Nib": 103,
                "Omamori": 111,
                "Letter Opener": 19,
                "Orichalcum": 105,
                "MawBank": 67,
                "SlaversCollar": 85,
                "CaptainsWheel": 103,
                "Bronze Scales": 105,
                "Black Star": 42,
                "Membership Card": 121
            }
        ],
        "InkBottle": [
            39
        ]
    },
    "card_choices": [
        {
            "not_picked": [
                "Metamorphosis",
                "Panache"
            ],
            "picked": "HandOfGreed",
            "floor": 0
        },
        {
            "not_picked": [
                "Clash",
                "Sword Boomerang"
            ],
            "picked": "Seeing Red",
            "floor": 1
        },
        {
            "not_picked": [
                "Sever Soul",
                "Rampage"
            ],
            "picked": "Dark Embrace",
            "floor": 4
        },
        {
            "not_picked": [
                "Clothesline",
                "Thunderclap"
            ],
            "picked": "Infernal Blade",
            "floor": 5
        },
        {
            "not_picked": [
                "Power Through",
                "Clothesline"
            ],
            "picked": "Battle Trance",
            "floor": 7
        },
        {
            "not_picked": [
                "Anger",
                "Shrug It Off"
            ],
            "picked": "Headbutt",
            "floor": 10
        },
        {
            "not_picked": [
                "Anger",
                "Clash",
                "Flex"
            ],
            "picked": "SKIP",
            "floor": 12
        },
        {
            "not_picked": [
                "Twin Strike",
                "Dark Embrace"
            ],
            "picked": "Shrug It Off",
            "floor": 14
        },
        {
            "not_picked": [
                "Demon Form",
                "Bludgeon"
            ],
            "picked": "Juggernaut",
            "floor": 16
        },
        {
            "not_picked": [
                "Cleave",
                "Sword Boomerang"
            ],
            "picked": "Carnage",
            "floor": 18
        },
        {
            "not_picked": [
                "Heavy Blade",
                "Clash+1",
                "Perfected Strike"
            ],
            "picked": "SKIP",
            "floor": 20
        },
        {
            "not_picked": [
                "Flying Knee",
                "Outmaneuver"
            ],
            "picked": "Sever Soul",
            "floor": 22
        },
        {
            "not_picked": [
                "Perfected Strike",
                "PathToVictory"
            ],
            "picked": "Endless Agony",
            "floor": 23
        },
        {
            "not_picked": [
                "Fasting2",
                "Beam Cell"
            ],
            "picked": "Burning Pact",
            "floor": 24
        },
        {
            "not_picked": [
                "Distraction",
                "Pray"
            ],
            "picked": "Storm of Steel",
            "floor": 29
        },
        {
            "not_picked": [
                "Cleave",
                "CutThroughFate"
            ],
            "picked": "Blade Dance",
            "floor": 30
        },
        {
            "not_picked": [
                "Shrug It Off",
                "Fire Breathing",
                "BowlingBash"
            ],
            "picked": "SKIP",
            "floor": 31
        },
        {
            "not_picked": [
                "Envenom",
                "Machine Learning"
            ],
            "picked": "Core Surge",
            "floor": 33
        },
        {
            "not_picked": [
                "Armaments",
                "Blind"
            ],
            "picked": "PiercingWail+1",
            "floor": 35
        },
        {
            "not_picked": [
                "Coolheaded",
                "WreathOfFlame"
            ],
            "picked": "Tantrum+1",
            "floor": 36
        },
        {
            "not_picked": [
                "Cloak And Dagger",
                "Sunder"
            ],
            "picked": "Master of Strategy",
            "floor": 37
        },
        {
            "not_picked": [
                "Barrage",
                "Evolve",
                "Headbutt+1"
            ],
            "picked": "SKIP",
            "floor": 40
        },
        {
            "not_picked": [
                "Barrage",
                "Evolve",
                "Headbutt+1"
            ],
            "picked": "SKIP",
            "floor": 40
        },
        {
            "not_picked": [
                "Poisoned Stab+1",
                "Perfected Strike"
            ],
            "picked": "FearNoEvil",
            "floor": 44
        },
        {
            "not_picked": [
                "ClearTheMind",
                "Streamline"
            ],
            "picked": "Study",
            "floor": 46
        },
        {
            "not_picked": [
                "Gash+1",
                "Acrobatics"
            ],
            "picked": "HandOfGreed",
            "floor": 48
        },
        {
            "not_picked": [
                "Crescendo",
                "Nirvana"
            ],
            "picked": "Seeing Red+1",
            "floor": 55
        }
    ],
    "player_experience": 7980034,
    "relics_obtained": [
        {
            "floor": 7,
            "key": "Red Skull"
        },
        {
            "floor": 9,
            "key": "Letter Opener"
        },
        {
            "floor": 12,
            "key": "WingedGreaves"
        },
        {
            "floor": 23,
            "key": "InkBottle"
        },
        {
            "floor": 23,
            "key": "Matryoshka"
        },
        {
            "floor": 24,
            "key": "Blue Candle"
        },
        {
            "floor": 24,
            "key": "Potion Belt"
        },
        {
            "floor": 26,
            "key": "MawBank"
        },
        {
            "floor": 30,
            "key": "Thread and Needle"
        },
        {
            "floor": 30,
            "key": "Dead Branch"
        },
        {
            "floor": 31,
            "key": "Pear"
        },
        {
            "floor": 31,
            "key": "Blood Vial"
        },
        {
            "floor": 40,
            "key": "CaptainsWheel"
        },
        {
            "floor": 40,
            "key": "Old Coin"
        },
        {
            "floor": 43,
            "key": "Pen Nib"
        },
        {
            "floor": 43,
            "key": "Ancient Tea Set"
        },
        {
            "floor": 44,
            "key": "Orichalcum"
        },
        {
            "floor": 44,
            "key": "Bronze Scales"
        },
        {
            "floor": 46,
            "key": "Mummified Hand"
        },
        {
            "floor": 46,
            "key": "Strawberry"
        },
        {
            "floor": 48,
            "key": "StoneCalendar"
        },
        {
            "floor": 48,
            "key": "Omamori"
        },
        {
            "floor": 55,
            "key": "Happy Flower"
        },
        {
            "floor": 55,
            "key": "Oddly Smooth Stone"
        }
    ],
    "event_choices": [
        {
            "damage_healed": 0,
            "gold_gain": 0,
            "player_choice": "Success",
            "damage_taken": 5,
            "relics_obtained": [
                "Centennial Puzzle"
            ],
            "max_hp_gain": 0,
            "max_hp_loss": 0,
            "event_name": "Scrap Ooze",
            "floor": 3,
            "gold_loss": 0
        },
        {
            "damage_healed": 0,
            "gold_gain": 0,
            "player_choice": "2 cards matched",
            "damage_taken": 0,
            "max_hp_gain": 0,
            "max_hp_loss": 0,
            "event_name": "Match and Keep!",
            "floor": 11,
            "gold_loss": 0,
            "cards_obtained": [
                "Berserk",
                "Bloodletting"
            ]
        },
        {
            "damage_healed": 0,
            "gold_gain": 50,
            "player_choice": "Stole From Cult",
            "damage_taken": 0,
            "max_hp_gain": 0,
            "max_hp_loss": 0,
            "event_name": "Nest",
            "floor": 19,
            "gold_loss": 0
        },
        {
            "cards_removed": [
                "Strike_R"
            ],
            "damage_healed": 0,
            "gold_gain": 0,
            "player_choice": "Card Removal",
            "damage_taken": 0,
            "max_hp_gain": 0,
            "max_hp_loss": 0,
            "event_name": "Wheel of Change",
            "floor": 27,
            "gold_loss": 0
        },
        {
            "damage_healed": 0,
            "gold_gain": 0,
            "player_choice": "Ignored",
            "damage_taken": 0,
            "max_hp_gain": 0,
            "max_hp_loss": 0,
            "event_name": "Tomb of Lord Red Mask",
            "floor": 39,
            "gold_loss": 0
        },
        {
            "damage_healed": 0,
            "gold_gain": 0,
            "player_choice": "Max HP",
            "damage_taken": 0,
            "max_hp_gain": 0,
            "max_hp_loss": 4,
            "event_name": "Winding Halls",
            "floor": 41,
            "gold_loss": 0
        }
    ],
    "is_beta": false,
    "boss_relics": [
        {
            "not_picked": [
                "Calling Bell",
                "Busted Crown"
            ],
            "picked": "Black Star"
        },
        {
            "not_picked": [
                "Snecko Eye",
                "Velvet Choker"
            ],
            "picked": "SlaversCollar"
        }
    ],
    "items_purged_floors": [
        2,
        21,
        38,
        54
    ],
    "is_endless": false,
    "potions_floor_spawned": [
        4,
        5,
        7,
        16,
        18,
        23,
        29,
        30,
        31,
        35,
        46,
        48,
        55
    ],
    "ascension_level": 20,
    "potion_discard_per_floor": [
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [
            "AttackPotion"
        ],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [
            "BlessingOfTheForge"
        ],
        [],
        [],
        []
    ]
}